program MaisEscola;

uses
  Forms,
  UDados in 'UDados.pas' {Dados: TDataModule},
  UUsuarios in 'UUsuarios.pas' {FUsuarios},
  UAbout in 'UAbout.pas' {FAbout},
  UAcervo in 'UAcervo.pas' {FAcervo},
  UAcervoReservas in 'UAcervoReservas.pas' {FAcervoReservas},
  UAcervoRetiradas in 'UAcervoRetiradas.pas' {FAcervoRetiradas},
  UAlergias in 'UAlergias.pas' {FAlergias},
  UAlunos in 'UAlunos.pas' {FAlunos},
  UAlunosInad in 'UAlunosInad.pas' {FAlunosInad},
  UAniv in 'UAniv.pas' {FAniv},
  UAtividades in 'UAtividades.pas' {FAtividades},
  UAutores in 'UAutores.pas' {FAutores},
  UBackUp in 'UBackUp.pas' {FBackUp},
  UBairros in 'UBairros.pas' {FBairros},
  UBaixaCarne in 'UBaixaCarne.pas' {FBaixaCarne},
  UCFOP in 'UCFOP.pas' {FCFOP},
  UCidades in 'UCidades.pas' {FCidades},
  UCompras in 'UCompras.pas' {FCompras},
  UComProdutos in 'UComProdutos.pas' {FComProdutos},
  UCondPgto in 'UCondPgto.pas' {FCondPgto},
  UConfig in 'UConfig.pas' {FConfig},
  UCorresp in 'UCorresp.pas' {FCorresp},
  UDatasCom in 'UDatasCom.pas' {FDatasCom},
  UDisciplinas in 'UDisciplinas.pas' {FDisciplinas},
  UDoencas in 'UDoencas.pas' {FDoencas},
  UEdAcervo in 'UEdAcervo.pas' {FEdAcervo},
  UEdAcervoDev in 'UEdAcervoDev.pas' {FEdAcervoDev},
  UEdAcervoItens in 'UEdAcervoItens.pas' {FEdAcervoItens},
  UEdAcervoRes in 'UEdAcervoRes.pas' {FEdAcervoRes},
  UEdAcervoRet in 'UEdAcervoRet.pas' {FEdAcervoRet},
  UEdAlergias in 'UEdAlergias.pas' {FEdAlergias},
  UEdAlunos in 'UEdAlunos.pas' {FEdAlunos},
  UEdAlunosAlergias in 'UEdAlunosAlergias.pas' {FEdAlunosAlergias},
  UEdAlunosBoletim in 'UEdAlunosBoletim.pas' {FEdAlunosBoletim},
  UEdAlunosDoencas in 'UEdAlunosDoencas.pas' {FEdAlunosDoencas},
  UEdAlunosFunc in 'UEdAlunosFunc.pas' {FEdAlunosFunc},
  UEdAlunosProd in 'UEdAlunosProd.pas' {FEdAlunosProd},
  UEdAlunosRemedios in 'UEdAlunosRemedios.pas' {FEdAlunosRemedios},
  UEdAlunosSaidas in 'UEdAlunosSaidas.pas' {FEdAlunosSaidas},
  UEdAlunosTrat in 'UEdAlunosTrat.pas' {FEdAlunosTrat},
  UEdAtividades in 'UEdAtividades.pas' {FEdAtividades},
  UEdAutores in 'UEdAutores.pas' {FEdAutores},
  UEdBairros in 'UEdBairros.pas' {FEdBairros},
  UEdCFOP in 'UEdCFOP.pas' {FEdCFOP},
  UEdCidades in 'UEdCidades.pas' {FEdCidades},
  UEdCondPgto in 'UEdCondPgto.pas' {FEdCondPgto},
  UEdCorresp in 'UEdCorresp.pas' {FEdCorresp},
  UEdDatasCom in 'UEdDatasCom.pas' {FEdDatasCom},
  UEdDisciplinas in 'UEdDisciplinas.pas' {FEDDisciplinas},
  UEdDoencas in 'UEdDoencas.pas' {FEdDoencas},
  UEdEditoras in 'UEdEditoras.pas' {FEdEditoras},
  UEdEstados in 'UEdEstados.pas' {FEdEstados},
  UEdFunc in 'UEdFunc.pas' {FEdFunc},
  UEdGen in 'UEdGen.pas' {FEdGen},
  UEdGeneros in 'UEdGeneros.pas' {FEdGeneros},
  UEdInv in 'UEdInv.pas' {FEdInv},
  UEditoras in 'UEditoras.pas' {FEditoras},
  UEdMovEst in 'UEdMovEst.pas' {FEdMovEst},
  UEdProdutos in 'UEdProdutos.pas' {FEdProdutos},
  UEdProfissoes in 'UEdProfissoes.pas' {FEdProfissoes},
  UEdRefeicoes in 'UEdRefeicoes.pas' {FEdRefeicoes},
  UEdRemedios in 'UEdRemedios.pas' {FEdRemedios},
  UEdTrat in 'UEdTrat.pas' {FEdTrat},
  UEdTurmas in 'UEdTurmas.pas' {FEdTurmas},
  UEdTurmasAtividades in 'UEdTurmasAtividades.pas' {FEdTurmasAtividades},
  UEdTurmasCalRef in 'UEdTurmasCalRef.pas' {FEdTurmasCalRef},
  UEdTurmasCardapio in 'UEdTurmasCardapio.pas' {FEdTurmasCardapio},
  UEdTurmasLancaDias in 'UEdTurmasLancaDias.pas' {FEdTurmasLancaDias},
  UEdUsuarios in 'UEdUsuarios.pas' {FEdUsuarios},
  UEstados in 'UEstados.pas' {FEstados},
  UEtiquetas in 'UEtiquetas.pas' {FEtiquetas},
  UFunc in 'UFunc.pas' {FFunc},
  UGen in 'UGen.pas' {FGen},
  UGeneros in 'UGeneros.pas' {FGeneros},
  UInv in 'UInv.pas' {FInv},
  ULancaCarne in 'ULancaCarne.pas' {FLancaCarne},
  UMalaDireta in 'UMalaDireta.pas' {FMalaDireta},
  UMovEst in 'UMovEst.pas' {FMovEst},
  UProdutos in 'UProdutos.pas' {FProdutos},
  UProfissoes in 'UProfissoes.pas' {FProfissoes},
  URefeicoes in 'URefeicoes.pas' {FRefeicoes},
  URelatoriosEst in 'URelatoriosEst.pas' {FRelatoriosEst},
  URelatoriosSint in 'URelatoriosSint.pas' {FRelatoriosSint},
  URemedios in 'URemedios.pas' {FRemedios},
  USaidas in 'USaidas.pas' {FSaidas},
  USistema in 'USistema.pas' {FSistema},
  UTelaIni in 'UTelaIni.pas' {FTelaIni},
  UTrat in 'UTrat.pas' {FTrat},
  UTurmas in 'UTurmas.pas' {FTurmas},
  UEdCompras in 'UEdCompras.pas' {FEdCompras},
  UEdComprasItens in 'UEdComprasItens.pas' {FEdComprasItens},
  UCPagar in 'UCPagar.pas' {FCPagar},
  UEdCP in 'UEdCP.pas' {FEdCP},
  UEdBancos in 'UEdBancos.pas' {FEdBancos},
  UBancos in 'UBancos.pas' {FBancos},
  UEdCPParcs in 'UEdCPParcs.pas' {FEdCPParcs},
  UEdCC in 'UEdCC.pas' {FEdCC},
  UCC in 'UCC.pas' {FCC},
  UBaixaCP in 'UBaixaCP.pas' {FBaixaCP},
  UEdCRParcs in 'UEdCRParcs.pas' {FEdCRParcs},
  UCReceber in 'UCReceber.pas' {FCReceber},
  UEdCR in 'UEdCR.pas' {FEdCR},
  UBaixaCR in 'UBaixaCR.pas' {FBaixaCR},
  URelatoriosFaixa in 'URelatoriosFaixa.pas' {FRelatoriosFaixa},
  UFichaAluno in 'UFichaAluno.pas' {FFichaAluno},
  UFichaFT in 'UFichaFT.pas' {FFichaFT},
  URelatoriosAn in 'URelatoriosAn.pas' {FRelatoriosAn},
  URelatoriosCompras in 'URelatoriosCompras.pas' {FRelatoriosCompras},
  URelatoriosCP in 'URelatoriosCP.pas' {FRelatoriosCP},
  UCheques in 'UCheques.pas' {FCheques},
  UEdCheques in 'UEdCheques.pas' {FEdCheques},
  URelatoriosCheques in 'URelatoriosCheques.pas' {FRelatoriosCheques};

{$R *.res}

begin
  try
    Application.Initialize;
    Application.Title := 'MaisEscola';                                                   
//    Application.CreateForm(TDados, Dados);
    FTelaIni := TFTelaIni.Create(nil); // (Application);
//    FTelaIni.Visible := False;
    FTelaIni.ShowModal;
  except
  end;
end.
